bg = "#fdf6e3"
fg = "#5c6a72"
accent = "#8da101"
panel_border = "#bdc3af"
panel_border_active = "#8da101"
selection_bg = "#e9e8d2"
cursor_bg = "#8da101"
cursor_fg = "#fdf6e3"
status_bar_bg = "#f0ebce"
status_bar_fg = "#5c6a72"
fn_key_bg = "#fdf6e3"
fn_key_fg = "#35a775"
header_fg = "#dfa000"
dir_fg = "#35a775"