bg = "#1b1817"
fg = "#d5c4a1"
accent = "#a89984"
panel_border = "#3c3836"
panel_border_active = "#fe8019"
selection_bg = "#32302f"
cursor_bg = "#fe8019"
cursor_fg = "#1b1817"
status_bar_bg = "#121111"
status_bar_fg = "#a89984"
fn_key_bg = "#1b1817"
fn_key_fg = "#d65d0e"
header_fg = "#83a598"
dir_fg = "#fabd2f"